### ISSUE TITLE
jffi*.tmp files remain in %TMP% folder

### ISSUE THREAD

**Issue by KloppsKopp** [jruby/jruby#1237]
Since the 1.7.5 release, every time jruby is instanciated, a new 115kb tempfile prefixed by 'JFFI' is created in the current user's %TMP%-folder and never cleaned up. 
This happens on multiple machines, all running windows 7 and oracle's java7 b43 or b10. 

Tested with jruby 1.7.5, 6, and 8. Doesn't occur in 1.7.3 and 1.7.4.

It occurs independently of how jruby is invoked on any launch and can lead to large disk pollution in machines that invoke jruby quite often.

**Comment by dialloa** [comment]
Hi Guys,

Can you please let me know in which version of jruby the issue is fixed?

I am using Logstash, i wan't to replace jruby-complete-1.7.11.jar with the right jar but i could not fine an information giving the right jar version. I downloaded 1.7.19 but not sure if it is fixed as i still have the jffi file created and not removed.

Thanks,
Abdoul

**Comment by rtyler** [comment]
@dialloa [JRuby 1.7.18](http://jruby.org/2014/12/22/jruby-1-7-18.html)

**Comment by dialloa** [comment]
Thanks rtyler. Greatly appreciated

**Comment by perlun** [comment]
Guess what... This bug is back now, in JRuby 9k. Will debug a bit more and then submit an issue (or hopefully, PR).
