### ISSUE TITLE
Nailgun output redirection on Windows

### ISSUE THREAD

**Issue by kradima** [jruby/jruby#1535]
When run rspec test using the nailgun server on Windows 7 the test output appears in the nailgun console, but not in the test console, which remains empty.

Expected that test output should be redirected into the test console.

Please note, on the Ubuntu everything works as expected - the test output appears on the test console rather than in the nailgun console.

**Comment by nodarsan** [comment]
I think this is still an issue.
On Windows 7 it seems all output is being done on the server console instead of the the client console as expected.

I found this ticket on the Nailgun repo that seems related: https://github.com/martylamb/nailgun/issues/13
it looks light they might have fixed the issue.

**Comment by headius** [comment]
I suspect this is a similar issue to what I fixed for Drip (#2690) in #4010. A similar fix for Nailgun is probably needed.

**Comment by actsasflinn** [comment]
I get the same issue on JRuby 9.1.5.0 on Mac OS X 10.11.6 with Java 1.7.0_45

**Comment by headius** [comment]
Those of you that have this problem...can you try to run with `-Xnative.enabled=false` and see what happens? I suspect it will work (though other things might break).

**Comment by headius** [comment]
If the fix for martylamb/nailgun#13 is also a fix for this issue, then all we should need to do is update the jruby-launcher with current nailgun sources and rebuild it.

@enebo I think you have built this before, yes? Perhaps you can try updating sources and reproducing this? I don't have a C/++ compiler set up on Windows at the moment.

**Comment by nodarsan** [comment]
I tried running the nailgun server `jruby -Xnative.enabled=false --ng-server` on Windows 7, but that did not seem to fix it.

**Comment by actsasflinn** [comment]
The issue seems to effect RHEL Linux 6.7 as well with jruby 9.0.0.0-pre1. Tried @headius suggestion and that seemed to work.

jruby -Xnative.enabled=false --ng-server

**Comment by actsasflinn** [comment]
This works on JRuby 9.1.5.0 on Mac OS X 10.11.6 with Java 1.7.0_45

`jruby -Xnative.enabled=false --ng-server`

**Comment by nmingotti** [comment]
The same issue appears for JRuby 9.2.6.0 in all these systems:

FreeBSD-11.2
Red Hat Enterprise Linux Server 7.6 (Maipo)
Debian GNU/Linux 9 (stretch)

The "-Xnative.enabled=false" method solved in all 3 system.

I guess it would be better to make "-Xnative.enabled=false" implicitely set when "jruby" is called with parameter "--ng-server".
