### ISSUE TITLE
Process.spawn using huge amounts of memory for simple script

### ISSUE THREAD

**Issue by djberg96** [jruby/jruby#3054]
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-06-15 0af53f6 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]

    # test.rb
    #!/usr/bin/env ruby
    puts "hello"
    warn "whut?"
    raise "oops!"

    # spawntest.rb
    file = File.join(__dir__, 'test.rb')
    Process.spawn(file, :out => ['test.log', 'a'])

    >ruby spawntest.rb
    Error: Your application used more memory than the safety cap of 500M.
    Specify -J-Xmx####m to increase it (#### = cap size in MB).
    Specify -w for full OutOfMemoryError stack trace

**Comment by bbrowning** [comment]
This looks like another bug in JRuby. In this case, there's a loop with a counter that never increments which means it's an infinite loop. The OOM just happens because it's infinitely adding entries into an ArrayList.

https://github.com/jruby/jruby/blob/2f324a7dfec7f4c0bc79b65b440e62bbe3167c64/core/src/main/java/org/jruby/util/io/PopenExecutor.java#L1083

The loop counter `i` is never being updated inside the body of the loop nor is the loop broken out of. It's probably just missing an `i++` at the end of the for statement itself.

**Comment by djberg96** [comment]
Yep, looks like it originally depended on an increment that has since been commented out.

**Comment by djberg96** [comment]
Fixed by https://github.com/jruby/jruby/pull/3061, thanks for merging!

**Comment by enebo** [comment]
Thanks for supplying the patch.  So do we pass on long spec run now with this change?  Certainly if we didn't it would be better than an infinite loop :)

**Comment by djberg96** [comment]
@enebo I'm not sure what you mean by a long spec run. Or were you talking to Ben?

**Comment by bbrowning** [comment]
@enebo This change fixed the OOM in the long spec run but it still fails with "Errno::ENOENT: No such file or directory - /scratch/jenkins/workspace/jruby-master-spec-ruby/rubyspec_temp/1582-kernel_spawn.txt" - see https://projectodd.ci.cloudbees.com/job/jruby-master-spec-ruby/43/console.
