### ISSUE TITLE
"invalid byte sequence in UTF-8" from shell command with binary output [JRuby-1.7.20.1/JRuby-9000]

### ISSUE THREAD

**Issue by lenny** [jruby/jruby#3195]
We recently updated some deployments from Java 6 to Java 7 and suddenly started seeing "invalid byte sequence in UTF-8” errors from some code we have that shells out to pdftk. I did some digging and discovered the reason for the behavior change between Java 6 and 7 was because ProcessManager is only used on Java > 1.6.

https://github.com/jruby/jruby/blob/1_7_20/core/src/main/ruby/jruby/kernel.rb#L17

The process_manager.rb code runs a gsub on the process output which can explode when the process outputs binary data (e.g. pdf). JRuby 1.7.20 and master.

https://github.com/jruby/jruby/blob/9adaca4eec9d66bdfddd45aa2631c8953c0c1e3f/core/src/main/ruby/jruby/kernel/jruby/process_manager.rb#L48

This seems incorrect to me and differs from MRI behavior (see below). I wouldn’t expect JRuby to munge process output. File a bug?

MRI:

1.9.3-p547 :001 > File.open('foo', 'w') { |f| f.write("\x92") }
 => 1
1.9.3-p547 :002 > `cat foo`
 => "\x92"

JRuby
jruby-1.7.20.1 :010 > File.open('foo', 'w') { |f| f.write("\x92") }
 => 1
jruby-1.7.20.1 :011 > `cat foo`
ArgumentError: invalid byte sequence in UTF-8

**Comment by lenny** [comment]
The obvious patch I'm applying locally is:

-      result.gsub(/\r\n/, "\n")
+      result

**Comment by lreimer** [comment]
I am having the same problemn and the cause in my environment is the file encoding system property.

After removing **-Dfile.encoding=UTF-8** from JAVA_OPTS everything works.

**Comment by rdp** [comment]
seems fixed in jruby-9.0.1.0 ?

**Comment by benjaminpmeier** [comment]
I'm seeing similar results when shelling out using jruby 1.7.11 (1.9.3p392) 2015-10-05 fffffff on Java HotSpot(TM) 64-Bit Server VM 1.8.0_60-b27 +indy [linux-amd64]

```
touch filename.txt�

irb(main):001:0> `ls`
ArgumentError: invalid byte sequence in UTF-8
 from org/jruby/RubyString.java:3078:in `gsub'
 ...
```
Removing that file fixes the problem.  Is this fixed in newer versions?

**Comment by headius** [comment]
@lreimer @benjaminpmeier Are either of you able to confirm that latest JRuby release works properly?

I'm not quite clear what the reproduction is here...can someone provide a script or git repo I can use?

**Comment by lreimer** [comment]
I will try to check with the latest jruby release.

**Comment by headius** [comment]
Any updates here?

**Comment by lenny** [comment]
Just re-ran the example in my original report again on 1.7.22 and 9.0.4.0.

I'm still able to reproduce in 1.7.22

```
jruby-1.7.22 :001 > File.open('foo', 'w') { |f| f.write("\x92") } && `cat foo`
ArgumentError: invalid byte sequence in UTF-8
	from org/jruby/RubyString.java:3101:in `gsub'
	from org/jruby/RubyString.java:3069:in `gsub'
	from file:/Users/lenny/.rvm/rubies/jruby-1.7.22/lib/jruby.jar!/jruby/kernel/jruby/process_manager.rb:47:in ``'
	from file:/Users/lenny/.rvm/rubies/jruby-1.7.22/lib/jruby.jar!/jruby/kernel/jruby/process_manager.rb:55:in ``'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1079:in `eval'
	from org/jruby/RubyKernel.java:1479:in `loop'
	from org/jruby/RubyKernel.java:1242:in `catch'
	from org/jruby/RubyKernel.java:1242:in `catch'
	from /Users/lenny/.rvm/rubies/jruby-1.7.22/bin/jirb:13:in `(root)'
```

but not on 9.0.4.0

```
jruby-9.0.4.0 :001 > File.open('foo', 'w') { |f| f.write("\x92") } && `cat foo`
 => "\x92" 
```

Although I don't quite understand why it's not still reproducible in 9.0.4.0 since the original offending code is still present.

https://github.com/jruby/jruby/blob/9.0.4.0/core/src/main/ruby/jruby/kernel/jruby/process_manager.rb#L48

```
jruby-9.0.4.0 :004 > `cat foo`.gsub(/\r\n/, "\n")
ArgumentError: invalid byte sequence in UTF-8
	from org/jruby/RubyString.java:2406:in `gsub'
	from org/jruby/RubyString.java:2374:in `gsub'
	from (irb):4:in `<eval>'
	from org/jruby/RubyKernel.java:978:in `eval'
	from org/jruby/RubyKernel.java:1291:in `loop'
	from org/jruby/RubyKernel.java:1098:in `catch'
	from org/jruby/RubyKernel.java:1098:in `catch'
```

How does that not happen before it returns at https://github.com/jruby/jruby/blob/9.0.4.0/core/src/main/ruby/jruby/kernel/jruby/process_manager.rb#L48
??

The gsub still seems wrong regardless of whether it triggers and invalid byte sequence error since that could still munge binary data. Also, it's different behavior than MRI.

```
# mri
2.2.1 :023 >   File.open('foo', 'w') { |f| f.write("\r\nfoo\r\n") } && `cat foo`.match(/\r\n/)
 => #<MatchData "\r\n"> 
```

```
jruby-9.0.4.0 :005 >  File.open('foo', 'w') { |f| f.write("\r\nfoo\r\n") } && `cat foo`.match(/\r\n/)
 => nil 
```

**Comment by lreimer** [comment]
I am also unable to reproduce the behaviour with 9.0.4.0. And the -Dfile.encoding=UTF-8 option does not matter anymore.

But I have updated my dev environment quite a bit since 5th Aug, so the conditions for my retest are not probably not the same anymore.
