### ISSUE TITLE
Respond_to? returns private methods

### ISSUE THREAD

**Issue by gaurish** [jruby/jruby#4253]
From Twitter: https://twitter.com/headius/status/788857979655323648
### Environment

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.101-b13 on 1.8.0_101-b13 +jit [darwin-x86_64]
The [test case](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activemodel/test/cases/attribute_assignment_test.rb#L80-L85):

```
test "assign private attribute" do
    model = Model.new
    assert_raises(ActiveModel::UnknownAttributeError) do
      model.assign_attributes(metadata: { a: 1 })
    end
  end

```
### Expected Behavior

raise `ActiveModel::UnknownAttributeError`
### Actual Behavior

```
Class: <NoMethodError>
Message: <"protected method `metadata=' called for #<AttributeAssignmentTest::Model:0x4203529f>">
---Backtrace---
org/jruby/RubyKernel.java:1820:in `public_send'
/Users/gaurish/code/repo/rails/activemodel/lib/active_model/attribute_assignment.rb:47:in `_assign_attribute'
/Users/gaurish/code/repo/rails/activemodel/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
org/jruby/RubyHash.java:1339:in `each'
/Users/gaurish/code/repo/rails/activemodel/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/Users/gaurish/code/repo/rails/activemodel/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
test/cases/attribute_assignment_test.rb:83:in `block in test_assign_private_attribute'
```

This there is a comment about this at https://github.com/jruby/jruby/blame/21b9760280f07fe91aa5a12f23334579b5744024/core/src/main/java/org/jruby/ext/ripper/RubyRipper.java#L361

**Comment by kares** [comment]
thanks, would be better to give it a go on JRuby 9.1.5.0 instead of 9.0.5.0 (that or a reduced test-case)

**Comment by kirs** [comment]
9.1.5.0 has the same issue:

```
class Post
  protected
  def metadata
  end
end
puts Post.new.respond_to?(:metadata).inspect


$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ ruby respond.rb
false


$ ruby -v
jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
$ ruby respond.rb
true
```

cc @headius

**Comment by kirs** [comment]
cc @enebo

**Comment by enebo** [comment]
@kirs this is fixed in 9.1.6.0.  Can you confirm that?

**Comment by kirs** [comment]
I confirm that ❤️ 
I'll update Rails to use 9.1.6.0.

I think the issue can be closed.

**Comment by kirs** [comment]
Ooops, I was wrong:

```
$ jruby -v
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
```

```ruby
# post.rb
class Post
  protected
  def metadata
  end
end
puts Post.new.respond_to?(:metadata).inspect
```

```
$ jruby post.rb
true
```

**Comment by enebo** [comment]
@kirs interestingly the bug we fixed in 9.1.6.0 was the exact opposite problem that we were not seeing true when we should have.   Thanks for checking.

**Comment by kirs** [comment]
Maybe you fixed it for private methods, but not for protected?

**Comment by enebo** [comment]
@kirs the fix was for protected methods and involved us not checking beneath a particular point due to the use of prepended modules.  We were getting false back and not true due to us not searching past the prepended module.  I read this issue backwards.

**Comment by kirs** [comment]
Thanks for the background! In my case above there're no prepended modules involved.

**Comment by kirs** [comment]
@enebo this is still an issue on master. Do you have any suggestion how I can fix it? It currently blocks us on the Rails side.
Thanks!

**Comment by enebo** [comment]
@kirs I will see if I can get any insight into this.  One weird thing is respond_to? even in a method of the same time returns true while mri will return false.  So post will really respond to being sent metadata but the respond_to? method will still say false?

**Comment by kirs** [comment]
@enebo not exactly. As a result, `respond_to? => true` on JRuby leads to `NoMethodError` being triggered:

```ruby
class Post
  protected
  def metadata
  end
end
post = Post.new
if post.respond_to?(:metadata)
  post.metadata
else
  puts "no metadata available"
end
```

```
$ bin/jruby respond.rb
NoMethodError: protected method `metadata' called for #<Post:0x4923ab24>
  <main> at respond.rb:8
```

While on MRI that works as expected:

```
$ chruby ruby-2.3.3
$ ruby respond.rb
no metadata available
```

**Comment by enebo** [comment]
@kirs I think I have this fixed locally.  Running tests now.  If appears for dispatch we only care about private visibility but for respond_to? we care about both private and protected.  It is a lack of symmetry.

**Comment by kirs** [comment]
Awesome. I'm looking forward for updates from you.

**Comment by enebo** [comment]
@kirs kick the tires on this one.  I did actually find some tagged out specs on this and I feel fairly confident about the fix but nonetheless this is pretty low-level language mojo :)

**Comment by kirs** [comment]
Thanks! ❤️ 
Now it works as expected.
