### ISSUE TITLE
The & operator doesn't work with quoted symbols

### ISSUE THREAD

**Issue by pcarlisle** [jruby/jruby#5066]
### Environment

jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a Java HotSpot(TM) 64-Bit Server VM 25.162-b12 on 1.8.0_162-b12 +jit [linux-x86_64]

Linux  4.14.14-1-ARCH #1 SMP PREEMPT Fri Jan 19 18:42:04 UTC 2018 x86_64 GNU/Linux

### Expected Behavior

```
% ruby -v
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
% irb
irb(main):001:0> (1..3).reduce(&:'+')
=> 6
irb(main):002:0> (1..3).map(&:'to_s')
=> ["1", "2", "3"]
irb(main):003:0> 
```

### Actual Behavior

```
irb(main):006:0> (1..3).reduce(&:+)
=> 6
irb(main):007:0> (1..3).reduce(&:'+')
NoMethodError: undefined method `+' for 1:Fixnum
	from org/jruby/RubyRange.java:495:in `each'
	from org/jruby/RubyEnumerable.java:931:in `inject'
	from (irb):7:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1316:in `loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /home/patrick/.rbenv/versions/jruby-9.1.16.0/bin/irb:13:in `<main>'
irb(main):008:0> method = :'+'
=> :+
irb(main):009:0> (1..3).reduce(&method)
=> 6

irb(main):012:0> (1..3).map(&:'to_s')
NoMethodError: undefined method `to_s' for 1:Fixnum
	from org/jruby/RubyRange.java:495:in `each'
	from org/jruby/RubyEnumerable.java:830:in `map'
	from (irb):12:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1316:in `loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /home/patrick/.rbenv/versions/jruby-9.1.16.0/bin/irb:13:in `<main>'
```

**Comment by pcarlisle** [comment]
Oh I tried searching before but now just found #3880 and related and this is probably the same

**Comment by headius** [comment]
Wow that's pretty weird. I'd expect this to work since the string part doesn't contain anything weird.

This, like #3880, is probably fixed by @enebo's almost-complete rework of strings, symbols, and identifiers (for 9.2).

Not sure if there's a workaround. I am surprised this doesn't work.

**Comment by pcarlisle** [comment]
The workaround seems to be saving the quoted symbol to a variable and calling with that (which maybe suggests it's not an encoding issue)

**Comment by enebo** [comment]
fwiw bytelist_love branch does work now but I also find this super weird that it is broken.  It is already ascii and a symbol.  Even with utf-8 as default this encoding should be US-ASCII.

**Comment by enebo** [comment]
Yeah this was just another case of pretending unsafeBytes() has begin of 0 and .length or realSize().  Almost hard to imagine any of these bugs could still exist...And bytelist_love is totally different now so this code I fixed does not exist there (and this works fine there).
