### ISSUE TITLE
Jruby 9.2.6 rake db:migrate error

### ISSUE THREAD

**Issue by jailalawat** [jruby/jruby#5792]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b OpenJDK 64-Bit Server VM 11.0.3+7-Ubuntu-1ubuntu218.04.1 on 11.0.3+7-Ubuntu-1ubuntu218.04.1 +jit [linux-x86_64]
* Operating system and platform (e.g. `uname -a`)
Linux jailalawat 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Other relevant info you may wish to add:
* Installed or activated gems
**rails -v**
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Rails 5.2.3
```
* Application/framework version (e.g. Rails, Sinatra)
Rails 5.2.3
* Environment variables
NO
### Expected Behavior
rake db:create not shown any errors.

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.
Create a simple ror project
gem install rails activerecord-jdbcpostgresql-adapter
rails new ncpi-emandate-auth -d postgresql
### Actual Behavior

**rake db:create**
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Created database 'ncpi-emandate-auth_development'
E, [2019-07-15T16:15:43.342998 #11541] ERROR -- : run() in thread failed: closed stream:\n org/jruby/RubyIO.java:3552:in `select'
org/jruby/RubyKernel.java:666:in `select'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:306:in `readpartial'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:279:in `read_events'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
org/jruby/ext/thread/Mutex.java:165:in `synchronize'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/forwardable.rb:229:in `start'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in Listener'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:96:in `boot!'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:67:in `initialize'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:166:in `block in Finisher'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:347:in `call'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:226:in `tsort_each'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/tsort.rb:205:in `tsort_each'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/jailalawat/Projects/NCPI/ncpi-emandate-auth/config/environment.rb:5:in `<main>'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/application.rb:1:in `(root)'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `block in require_environment!'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:214:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:238:in `each'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:238:in `invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:236:in `block in invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:213:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:238:in `each'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:238:in `invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:236:in `block in invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:213:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:160:in `block in invoke_task'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in each'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:116:in `top_level'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:110:in `block in top_level'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:83:in `run'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/jailalawat/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rake-12.3.2/lib/rake/application.rb:80:in `<main>'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0@global/bin/rake:23:in `load'
/home/jailalawat/.rvm/gems/jruby-9.2.6.0@global/bin/rake:23:in `<main>'
warning: thread "Ruby-0-Thread-4: /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6" terminated with exception (report_on_exception is true):
IOError: closed stream
       select at org/jruby/RubyIO.java:3552
       select at org/jruby/RubyKernel.java:666
  readpartial at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:306
  read_events at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:279
      process at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252
          run at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229
  synchronize at org/jruby/ext/thread/Mutex.java:165
          run at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226
         _run at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39
        start at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:78
          add at /home/jailalawat/.rvm/gems/jruby-9.2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6
```

**Comment by jailalawat** [comment]
java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing

**Comment by kares** [comment]
those are just warnings, your DB is being created: *Created database 'ncpi-emandate-auth_development'*
update to latest 9.2.7 ... you might have less of the reflective warnings, except maybe for the last one ...

**Comment by enebo** [comment]
The IOError should not be present in 9.2.7.0.  Even in 9.2.6.0 this error was only happening shutting down listen gem after the command had finished.

**Comment by headius** [comment]
Already fixed via changes in JRuby (and in rb_inotify I believe, right @enebo?)

**Comment by enebo** [comment]
@headius not fixed in rb_inotify but Rails in later versions I believe does not depend on implicit finalization in GC (or at least somehow the issue no longer happens).

**Comment by jailalawat** [comment]
@headius If already fixed then why it is happened again in newer version

**Comment by enebo** [comment]
@jailalawat have you tried 9.2.7.0.  It should work.  You reported against 9.2.6.0.

**Comment by jailalawat** [comment]
@enebo Still have a problem with jruby-9.2.7.0 and rails 5.2.3

E, [2019-08-30T15:57:52.321502 #4123] ERROR -- : run() in thread failed: closed stream:\n org/jruby/RubyIO.java:1493:in `fileno'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fd'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:275:in `read_events'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
org/jruby/ext/thread/Mutex.java:165:in `synchronize'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/forwardable.rb:229:in `start'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in Listener'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:96:in `boot!'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:67:in `initialize'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/i18n_railtie.rb:61:in `initialize_i18n'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/i18n_railtie.rb:19:in `block in Railtie'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/application/finisher.rb:75:in `block in Finisher'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:347:in `call'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:226:in `tsort_each'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/tsort.rb:205:in `tsort_each'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/jailalawat/Projects/E-Mandate/config/environment.rb:5:in `<main>'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/application.rb:1:in `(root)'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/application.rb:337:in `block in require_environment!'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@E-Mandate/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:214:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:238:in `each'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:238:in `invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:236:in `block in invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:213:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:238:in `each'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:238:in `invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:236:in `block in invoke_prerequisites'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:213:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:160:in `block in invoke_task'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in each'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:116:in `top_level'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:110:in `block in top_level'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:83:in `run'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/jailalawat/.rvm/rubies/jruby-9.2.7.0/lib/ruby/gems/shared/gems/rake-12.3.3/lib/rake/application.rb:80:in `<main>'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@global/bin/rake:23:in `load'
/home/jailalawat/.rvm/gems/jruby-9.2.7.0@global/bin/rake:23:in `<main>'

**Comment by enebo** [comment]
@jailalawat and this was at the end of the db:migrate or something else?  I have not seen this on 5.2.3 so I had assumed something had changed in how rb0inotify is used.

**Comment by jailalawat** [comment]
@enebo Its always happened with rake db:migrate or any generator we are using.
Here is some information 
jailalawat@jailalawat:~/Projects/$ jruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10 +jit [linux-x86_64]
jailalawat@jailalawat:~/Projects/$ rails -v
Rails 5.2.3
jailalawat@jailalawat:~/Projects/$ javac -version
javac 1.8.0_222
jailalawat@jailalawat:~/Projects$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
