### ISSUE TITLE
set_trace_func library working differently on JRuby

### ISSUE THREAD

**Issue by 0x1eef** [jruby/jruby#6096]
After having a chat with @headius , I decided to give one of my projects a shot on JRuby.

The first thing we noticed was that `Thread#set_trace_func` was not implemented.
This didn't turn out to be a show stopper as I was able to emulate `Thread#set_trace_func` with `Kernel#set_trace_func` instead.

The second thing we noticed was that on JRuby, `Kernel#set_trace_func` emitted slightly different events than CRuby: CRuby emits `c-call` and `c-return` while JRuby emits `c_call` and `c_return`. This also wasn't a show stopper.

After adding a work-around for the first issue & brushing off the second as it's easily worked around / fixed, all specs on my project pass, except one spec and that's what I'd like to open an issue about.

### Steps to reproduce

1. git clone https://github.com/rg-3/trip.rb
2. cd trip.rb
3. git checkout jruby
4. bundle install
5. jruby --debug -S rspec spec/

Expect 3 failures, two about `c-call` / `c-return` issue mentioned above and a third one, which indicates that changes made in the `Binding` provided by `set_trace_func` do not propagate to the next event. That is, changes made during the `call` event (Ruby call, not `c-call`) do not propagate to the `return` event:

```
  3) Trip::Event#binding changes value of "x"
     Failure/Error: expect(event.binding.eval('sum')).to eq(9)
     
       expected: 9
            got: 7
     
       (compared using ==)
     # ./spec/trip_event_spec.rb:89:in `block in <main>'
```

I should add, my project is suspending the thread running `set_trace_func` and using `Binding#eval` to make changes, before resuming and allowing the `return` event transpire. On JRuby, the changes made in the Binding are not seen at the next event, though. I haven't digged into it much, but that's how it looks from the spec failure. It's also possible that Thread suspension is not working the same on JRuby, I'm not really sure.

Any help is appreciated. I've come from the tests hanging, to having only 1 spec failure to worry about, so it'd be great if my project could work on JRuby!

TODO:

* [x] Thread#set_trace_func
* [x] Fix event names
* [ ] Make changes to trace binding visible

**Comment by headius** [comment]
I'm pretty sure the `c-call` vs `c_call` issue has been fixed and `Thread.set_trace_func` added by @enebo. Could you reconfirm and see how we're doing now?

**Comment by rg-3** [comment]
@headius Sure, should I use jruby-head ?

**Comment by rg-3** [comment]
@headius 

Running the tests on master of [rg-3/trip.rb](https://github.com/rg-3/trip.rb), I see the failure originally outlined when i opened this issue, and a new failure related to the test of a thread being asleep or not.

```
▶ jruby -v --debug -S rspec
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-05-15 87104fdb1d OpenJDK 64-Bit Server VM 25.252-b09 on 1.8.0_252-8u252-b09-1~18.04-b09 +jit [linux-x86_64]
.........F.......F............

Failures:

  1) Trip::Event#binding changes value of "x"
     Failure/Error: expect(event.binding.eval('sum')).to eq(9)
     
       expected: 9
            got: 7
     
       (compared using ==)
     # ./spec/trip_event_spec.rb:89:in `block in <main>'

  2) Trip#sleeping? returns false
     Failure/Error: expect(trip).to_not be_sleeping
       expected `#<Trip:0x7ae42ce3 @block=#<Proc:0x4f5991f6@/home/rg/code/me/trip.rb/spec/trip_spec.rb:18>, @caller=#<...trip.rb:119 sleep>, @pause_when=#<Proc:0x602e0143@/home/rg/code/me/trip.rb/lib/trip.rb:24 (lambda)>>.sleeping?` to return false, got true
     # ./spec/trip_spec.rb:60:in `block in <main>'

Finished in 0.40912 seconds (files took 1.84 seconds to load)
30 examples, 2 failures

Failed examples:

rspec ./spec/trip_event_spec.rb:85 # Trip::Event#binding changes value of "x"
rspec ./spec/trip_spec.rb:57 # Trip#sleeping? returns false
```

I can confirm that `Thread#set_trace_func` has been implemented, and that the correct event names are passed to its Proc. Still other issues remain.
