### ISSUE TITLE
Sorbet `srb init` crashes

### ISSUE THREAD

**Issue by ilikeorangutans** [jruby/jruby#6242]
**Environment Information**
  
Provide at least:
* JRuby version: jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 25.252-b09 on 1.8.0_252-b09 +jit [darwin-x86_64]  
* Operating system and platform: Darwin MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

Other relevant info you may wish to add:
* Installed or activated gems: sorbet, locked to `0.5.5675`
```
gem 'sorbet-runtime'
gem 'sorbet', :group => :development
```
* Application/framework: none
* Environment variables: nothing unusual here; RUBY_ROOT, GEM_ROOT, GEM_PATH...

**Expected Behavior**

* Running `bundle exec srb init` should set up sorbet's config and RBIs
* Followed the steps here: https://sorbet.org/docs/adopting

**Actual Behavior**

`srb init` consistently crashes with the following error:

```
Naming Object/Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/real_stdlib.rb:77: warning: constant ::NativeException is deprecated
Naming JRuby/Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/real_stdlib.rb:77: warning: constant JRuby::IR is deprecated
Generating /var/folders/j8/w10tktnj6514v501c6lh_kw80000gn/T/d20200526-75253-1t3issx/reflection.rbi with 700 modules and 26 aliases
TypeError: bind argument must be an instance of Class
             bind at org/jruby/RubyUnboundMethod.java:120
  real_superclass at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/real_stdlib.rb:62
  class_or_module at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/serialize.rb:50
   gen_source_rbi at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:91
             each at org/jruby/RubyArray.java:1809
   gen_source_rbi at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:90
   capture_stderr at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:402
   gen_source_rbi at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:89
             main at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:45
             main at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:38
        make_step at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/bin/srb-rbi:232
             init at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/bin/srb-rbi:121
             main at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/bin/srb-rbi:196
           <main> at /Users/jakob/.gem/jruby/2.5.7/gems/sorbet-0.5.5675/bin/srb-rbi:237
```

**Comment by headius** [comment]
It looks like this is tripping over the special modules we set up to represent JRuby packages. I added logging to real_stdlib.rb and the final output looks like this:

```
XXXXXXXXXXXXXXXXXXX object is Java::JavaMethod
XXXXXXXXXXXXXXXXXXX object is Java::JavaObject
XXXXXXXXXXXXXXXXXXX object is Java::JavaPackage
TypeError: bind argument must be an instance of Class
             bind at org/jruby/RubyUnboundMethod.java:120
  real_superclass at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/lib/real_stdlib.rb:63
```

These modules are a bit complicated; they are not really a proper Ruby class but leverage the logic for including a module into a pseudo-class. This structure is not seen as a proper class and so binding a method from Class does not work.

I can reproduce the same error with a short snippit of code:

```
$ jruby -e 'Class.instance_method(:superclass).bind(java.lang.class)'
TypeError: bind argument must be an instance of Class
    bind at org/jruby/RubyUnboundMethod.java:120
  <main> at -e:1

[] ~/projects/csv $ jruby -e 'p java.lang.class'
Java::JavaPackage
```

Note we have other bugs about this peculiar structure, like #5784. This may be the push we need to finally make these objects look more like normal classes.

**Comment by headius** [comment]
I have pushed #6243 to try to reduce some of the magic we put round Java package modules. In that PR, those modules are simply subclasses of Module, which allows methods like `class` to work and allows Sorbet to run to completion (I think).

@ilikeorangutans Perhaps you could try a build from that branch and see if it works for you? I ran it against the csv library and it appear to run all the way to a final error unrelated to this one, where previously it blew up early on. I do not know enough about Sorbet to know if this final error is something you'd expect to see:

```
...
Zlib::NeedDict
Zlib::StreamEnd
Zlib::StreamError
Zlib::VersionError
Zlib::ZStream
Printing your code's symbol table into /var/folders/cq/ylcgmnn556x33f5hsqd0h54h0000gn/T/d20200526-51627-1ybk285/from-source.json
Printing /var/folders/cq/ylcgmnn556x33f5hsqd0h54h0000gn/T/d20200526-51627-1ybk285/reflection.rbi's symbol table into /var/folders/cq/ylcgmnn556x33f5hsqd0h54h0000gn/T/d20200526-51627-1ybk285/reflection.json
RuntimeError: /var/folders/cq/ylcgmnn556x33f5hsqd0h54h0000gn/T/d20200526-51627-1ybk285/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/cq/ylcgmnn556x33f5hsqd0h54h0000gn/T/d20200526-51627-1ybk285/reflection.json.err
  write_constants at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:149
             main at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:47
             main at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/lib/hidden-definition-finder.rb:38
        make_step at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/bin/srb-rbi:232
             init at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/bin/srb-rbi:121
             main at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/bin/srb-rbi:196
           <main> at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/sorbet-0.5.5675/bin/srb-rbi:237
```

**Comment by headius** [comment]
This is still an outstanding issue and I am unsure of the best solution. Likely to get punted off 9.3 release.

**Comment by enebo** [comment]
This is the code which hits the method which breaks...if I print out a package instance it prints out 'Module'.  Why is real_superclass called here?

```ruby
    superclass = Sorbet::Private::RealStdlib.real_is_a?(klass, Class) ? Sorbet::Private::RealStdlib.real_superclass(klass) : nil
```

I do believe if we fix this we will likely still not work because there appears to be several other methods in #5784 that are expected to be there.  With that said, I don't get why this is running a real_is_a? and returning true for our JI packages?

**Comment by enebo** [comment]
Note if I isolate this:

```text
jruby -rjava -e '@real_is_a ||= Object.instance_method(:is_a?);  p @real_is_a.bind(Java::Package).call(Class)'
```

This prints out false yet it prints out true in srb.  So either display of a package it printing out Java::Package and it is not in fact Java::Package or something strange is happening.
